server:
  port: 8080

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/credit_proposal?allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=true&createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: root

  jackson:
    serialization:
      fail-on-empty-beans: false

swagger:
  base-package: com.credit.analysis
  title: Credit Proposal API
  description: Credit Proposal API Documentation
  version: 1.0
  terms: Terms of Service
  develloper-name: Bruno Konzen Stahl
  develloper-email: bkstahl@gmail.com
  licence: Apache License Version 2.0
  licence-url: https://www.apache.org/licesen.html